language: node_js
node_js:
  - "0.12.4"

deploy:
  provider: built
  api-key: "GITHUB OAUTH TOKEN"
  file:
    - "public/js/mind-map-built.js"
    - "public/js/mind-map-built.js.map"
  skip_cleanup: true
  on:
    tags: true