language: node_js
node_js:
  - "0.12.4"

# blacklist
branches:
  except:
    - built-files

addons:
  ssh_known_hosts: bubl.guru

before_install:
openssl aes-256-cbc -K $encrypted_bb9043306a09_key -iv $encrypted_bb9043306a09_iv -in id_rsa.enc -out id_rsa -d

after_success:
    - chmod 600 id_rsa
    - ssh-add id_rsa
    - scp public/js/mind-map-built* continuous_integration@bubl.guru:builds