language: node_js
node_js:
  - "0.12.4"

# blacklist
branches:
  except:
    - built-files

before_install:
- openssl aes-256-cbc -K $encrypted_97f757139999_key -iv $encrypted_97f757139999_iv -in ssh.enc -out ssh -d

after_success:
    - chmod 600 ssh
    - ssh-add ssh
    - git clone -b built-files https://github.com/VincentBlouin/bubl.guru_mind-map built-files
    - mv public/js/mind-map-built* built-files
    - cd built-files
    - git add .
    - git commit -m "built files"
    - git push deploy