language: node_js
node_js:
  - "0.12.4"

# blacklist
branches:
  except:
    - built-files

addons:
  ssh_known_hosts: bubl.guru

before_install:
- openssl aes-256-cbc -K $encrypted_97f757139999_key -iv $encrypted_97f757139999_iv -in .travis/ssh.enc -out ssh -d

after_success:
    - chmod 600 ssh
    - ssh-add ssh
    - scp public/js/mind-map-built* continuous_integration@bubl.guru:builds